export const players = [
{ id: 0, name: "Luka Modric", club: "Real Madrid"},
{ id: 1, name: "Cristiano Ronaldo", club: "Juventus"},
{ id: 2, name: "Antoine Griezmann", club: "Atlético Madrid"},
{ id: 3, name: "Kylian Mbappé", club: "PSG"},
{ id: 4, name: "Lionel Messi", club: "Barcelona"},
{ id: 5, name: "Mohamed Salah", club: "Liverpool"},
{ id: 6, name: "Raphael Varane", club: "Real Madrid"},
{ id: 7, name: "Eden Hazard", club: "Chelsea"},
{ id: 8, name: "Kevin de Bruyne", club: "Man City"},
{ id: 9, name: "Harry Kane", club: "Tottenham"},
{ id: 10, name: "N'Golo Kante", club: "Chelsea"},
{ id: 11, name: "Neymar", club: "PSG"},
{ id: 12, name: "Luis Suarez", club: "Barcelona"},
{ id: 13, name: "Thibaut Courtois", club: "Real Madrid"},
{ id: 14, name: "Paul Pogba", club: "Man Utd"},
{ id: 15, name: "Sergio Aguero", club: "Man City"},
{ id: 16, name: "Karim Benzema", club: "Real Madrid"},
{ id: 17, name: "Gareth Bale", club: "Real Madrid"},
{ id: 18, name: "Ivan Rakitic", club: "Barcelona"},
{ id: 19, name: "Sergio Ramos", club: "Real Madrid"},
{ id: 20, name: "Roberto Firmino", club: "Liverpool"},
{ id: 21, name: "Marcel", club: "Real Madrid"},
{ id: 22, name: "Sadio Mane", club: "Liverpool"},
{ id: 23, name: "Edinson Cavani", club: "PSG"},
{ id: 24, name: "Jan Oblak", club: "Atletico Madrid"},
{ id: 25, name: "Alisson Becker", club: "Liverpool"},
{ id: 26, name: "Mario Mandzukic", club: "Juventus"},
{ id: 27, name: "Diego Godin", club: "Atletico Madrid"},
{ id: 28, name: "Hugo Lloris", club: "Tottenham"},
{ id: 29, name: "Isco", club: "Real Madrid"},
]